version: "3.3"
networks:
    local:

services:
    mysql:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        container_name: sejacarclub_db
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: blocks_db
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql_data:/var/lib/mysql
        networks:
            - local

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass secret
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - local
